version: '3'
services:
  api:
    build:
        context: ./
        dockerfile: docker/api/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres@postgres/kitchentable
  ui:
    build:
        context: ./
        dockerfile: docker/ui/Dockerfile
    command: yarn start
    volumes:
      - .:/usr/src/app
    ports:
      - "4200:4200"
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kitchentable
